# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Seminar-4th-review' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Seminar-4th-review
  pod 'Alamofire', '~> 5.2'
end
